### ISSUE TITLE
org.apache.jena.ontology.ConversionException

### ISSUE THREAD

**Issue by eroux** [Galigator/openllet#17]
When running the following code with openllet 2.6.1:

```java
String ontostring = "@prefix : <http://purl.bdrc.io/ontology/> .\n" + 
       "@prefix bdo: <http://purl.bdrc.io/ontology/> .\n" + 
       "@prefix owl: <http://www.w3.org/2002/07/owl#> .\n" + 
       "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n" + 
       "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n" + 
       "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n" + 
       "@base <http://purl.bdrc.io/ontology/> .\n" + 
       "\n" + 
       "<http://purl.bdrc.io/ontology/> rdf:type owl:Ontology ;\n" + 
       "                                 rdfs:label \"BDRC Ontology\"^^xsd:string ;\n" + 
       "                                 owl:versionInfo \"0.1\"^^xsd:string .\n" + 
       "\n" + 
       "bdo:personKinWho rdf:type owl:ObjectProperty ,\n" + 
       "                          owl:FunctionalProperty ;\n" + 
       "                 rdfs:domain bdo:Kin ;\n" + 
       "                 rdfs:range bdo:Person .\n" + 
       "\n" + 
       "\n" + 
       "bdo:Kin rdf:type owl:Class .\n" + 
       "\n" + 
       "bdo:Person rdf:type owl:Class .";
OntModel m = ModelFactory.createOntologyModel(OntModelSpec.OWL_DL_MEM);
InputStream stream = new ByteArrayInputStream(ontostring.getBytes());
m.read(stream, null, "TURTLE");
ExtendedIterator<OntProperty> ppi = m.listAllOntProperties();
while (ppi.hasNext()) {
        OntProperty p = ppi.next();
}
OntModel ontoModelInferred = ModelFactory.createOntologyModel(PelletReasonerFactory.THE_SPEC, m);
ppi = ontoModelInferred.listAllOntProperties();
while (ppi.hasNext()) { // ERROR
        OntProperty p = ppi.next();
}
```

I get:

```
org.apache.jena.ontology.ConversionException: Cannot convert node http://www.w3.org/2002/07/owl#bottomObjectProperty to TransitiveProperty
```

at the line marked with `// ERROR`.

The error goes away if I don't give the property the type `owl:FunctionalProperty`.

**Comment by Galigator** [comment]
I don't have check if it is legal for the reasoner to provide a bottomObjectProperty in this situation. But I am sure that it is OWL2 vocabulary(FunctionalProperty & bottomObjectProperty), so Jena may have problem with it.

**Comment by Galigator** [comment]
Maybe, we could want the reasonner to filter OWL2 answers when use with Jena.

**Comment by eroux** [comment]
Ok, I've opened an issue on the Jena tracker: https://issues.apache.org/jira/browse/JENA-1380 don't hesitate to comment.

**Comment by eroux** [comment]
It seems Jena doesn't support OWL2 indeed, it would probably be best to have an option in Openllet for OWL1-only inference.

**Comment by Galigator** [comment]
I think the best think to do is to build your OntModel like that : 
```

		OntModel ontoModelInferred = ModelFactory.createOntologyModel(PelletReasonerFactory.THE_SPEC, m);
		ontoModelInferred.setStrictMode(false);

```
Strictness is for correction, but here the correction rely on the reasoner, so there is no risk to disable it.
As Dave Reynolds told, it may take long before someone to the job; but the day Jena will have an OntModel for OWL2 it will be only one line to change (or nothing to change).

Another way to go should be to build an InfModel :
```

		final Reasoner reasoner = PelletReasonerFactory.theInstance().create();
		final Model emptyModel = ModelFactory.createDefaultModel();
		final InfModel model = ModelFactory.createInfModel(reasoner, emptyModel);
		model.read(stream, null, "TURTLE");

```
And then use a 'statement' oriented style.

You can also use the query.sparqld feature. There is no example but you can look at the tests https://github.com/Galigator/openllet/blob/integration/tests/src/test/java/openllet/test/query/TestMiscQueries.java#L140   (grep -rn "sparqldl"  openllet/tests   ; there is like ~100 tests)

**Comment by Galigator** [comment]
I have add an example to help people doing OWL2 with Jena :
[Here is the trick for OWL2](https://github.com/Galigator/openllet/blob/integration/examples/src/main/java/openllet/examples/JenaOwl2_Example.java)
