### ISSUE TITLE
Protege Plugin does not work

### ISSUE THREAD

**Issue by jpdigital** [Galigator/openllet#18]
When copying the openllet-protege-2.6.2-SNAPSHOT.jar or an earlier version to the Protege plugin directory Protege reports an error:

```
Error starting file:/home/jensp/protege/plugins/openllet-protege-2.6.2-SNAPSHOT.jar 
org.osgi.framework.BundleException: Unresolved constraint in bundle openllet-protege [45]: Unable to resolve 45.0: missing requirement [45.0] osgi.wiring.bundle; (&(osgi.wiring.bundle=org.semanticweb.owl.owlapi)(bundle-version>=5.1.0))
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2045) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299) ~[org.apache.felix.main.jar:na]
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304) [org.apache.felix.main.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

I suspect the reason for this is that Protege still uses the OWLAPI version 4, but Openllet and its Protege plugin already use version 5 of the OWLAPI.

If I'm correct I would suggest to put at least some warning into the readme.

Thanks, Jens

**Comment by Galigator** [comment]
Yes you are right, this is a version problem.
I will add a warning about this.


By the way I have done some change in protege to make it work with owlapi5 :
     https://github.com/Galigator/protege

As the pull-request (https://github.com/protegeproject/protege/pull/633), have been suspended/rejected, I don't have push all the stuff that make it work (And in fact I never use Protege), but if you really need it this is a good point to start from. Not sure if remaining problems come from Protege or Openllet.

One day Openllet will be transform into a more OSGI oriented project; not sure where to find time to do this.
