### ISSUE TITLE
no cli version?

### ISSUE THREAD

**Issue by seebi** [Galigator/openllet#23]
there was a pellet-cli.jar available.
do you plan to release a similar tool?

**Comment by Galigator** [comment]
The pellet-cli is still available.
It is available [here](https://github.com/Galigator/openllet/tree/integration/tools-cli).
The compilation of this tools is done when you compile the project (mvn clean install).
If you don't want to integrate the CLI into another tool, you can use the scripts "openllet.sh" and "openllet.bat".

**Comment by mileswhen** [comment]
Hi @Galigator,

Related question. I just used `mvn clean install` in the tools-cli directory. If I want to have the CLI as a .jar file and not use the openllet executable then how do I do that?

Thanks in advance
