### ISSUE TITLE
Inverse Functions create InternalReasonerException

### ISSUE THREAD

**Issue by GANys** [Galigator/openllet#25]
Hi, first let me thank you for your efforts to keep the Pellet project alive !

I've made some tests and I'm facing a known problem just as [https://github.com/Galigator/openllet/issues/22](url) did.

It seems the Inverse Functions are problematic. Here is the error I get : 

`Exception in thread "main" openllet.core.exceptions.InternalReasonerException: Invalid term found FunInv(http://www.geo.ulg.ac.be/nys/hasItem)`

Before that, another ObjectProperty was problematic, I created its inverse function and all seems working fine, until this new error appeared. But the inverse of hasItem has already been created. I don't know how to deal with it.

The problem is only Openllet with Jena shows me such an error (Pellet in Protégé doesn't).

I don't know if i'm explicit enough :/ Thank you in advance,

GA

**Comment by Galigator** [comment]
Indeed this look like the same exception, but the issue as become a junit test case; so I am not sure It is the same problem.

Can you give a try using the following option (before creating the reasoner)  ?
`OpenlletOptions.RETURN_NON_PRIMITIVE_EQUIVALENT_PROPERTIES = false`

This may be related to a recent change (or not). In both cases, to debug this I will need an ontology that produce enable the exception.

**Comment by GANys** [comment]
Hi,

After setting this option to false, the problem is no longer encoutered. Thanks.

The problem is I am working on a protected project, perhaps is there a way to communicate you my ontology without letting everybody access to it?

Kinds regards,

GA

**Comment by Galigator** [comment]
You can send a email to `openllet@gmail.com`

**Comment by Galigator** [comment]
Should work on lastest snapshot now.
