### ISSUE TITLE
Error : Built-In for SWRL

### ISSUE THREAD

**Issue by GANys** [Galigator/openllet#26]
Hi, I wanna know if there is a list of Built-In for SWRL that aren't supported by Openllet.

It is "only" a warning but the rule is quite important in my Ontology !

`2017-10-31 18:12:06 WARNING openllet.core.KnowledgeBaseImpl consistency Ignoring rule Rule(bnode(-7972c0ca:15f736b33a9:-7fb1) [hasPreviousItem(?x,?y), hasInput(?x,?a), hasOutput(?y,?b), differentFrom([?a, ?b])] => [hasError(?x,"Error : The I/O Data are not valid."^^string)]): No builtin for http://www.w3.org/2002/07/owl#differentFrom`

The rule is enabled in Protégé using Pellet.

Thank you in advance !

**Comment by Galigator** [comment]
There is no real differences in the support of swrl built-in between pellet and openllet.

**Comment by GANys** [comment]
Actually, the differentFrom predicate is not part of SWRL but of OWL. So my question was stupid right from the start...

```
owl:differentFrom a rdf:Property ;
     rdfs:label "differentFrom" ;
     rdfs:comment "The property that determines that two given individuals are different." ;
     rdfs:domain owl:Thing ;
     rdfs:isDefinedBy <http://www.w3.org/2002/07/owl#> ;
     rdfs:range owl:Thing . 
```

**Comment by GANys** [comment]
I don't get it.

I do understand why the rule doesn't work: it is not strict enough for the open world assumption. But that is my conception of the rule that I need to work on.

Am I supposed to create this rule by myself?

**Comment by GANys** [comment]
I don't get it.

I do understand why the rule doesn't work: it is not strict enough for the open world assumption. But that is my conception of the rule that I need to work on.

Am I supposed to create this owl:differentFrom by myself?

**Comment by Galigator** [comment]
No, your aren't supposed to create owl:differentFrom by youself. It should work out of the box.

Here an example of ontology that is using owl:differentFrom in a simple swrl rule  (?A-p-x , ?B-p-y, x > y, differentFrom([?A,?B]) --> ?A-sup-?B ).
[test.ttl.zip](https://github.com/Galigator/openllet/files/1440730/test.ttl.zip)

**Comment by GANys** [comment]
Oh. I found my mistake.

You have to write it `DifferentFrom` instead of `owl:differentFrom`.

My bad, thanks a lot !
