### ISSUE TITLE
Openllet can't be used in Wildfly/Thorntail

### ISSUE THREAD

**Issue by jpdigital** [Galigator/openllet#40]
I'm trying to use Openllet in a Java EE application running in Wildfly/Thorntail. This is currently not possible because Openllet calls `java.util.logging.Logger#setParent(Logger)` which is not allowed by Wildfly:

<pre>
Caused by: java.lang.SecurityException: setParent() disallowed
        at org.jboss.logmanager.Logger.setParent(Logger.java:359)
        at openllet.core.boxes.tbox.impl.TgBox.<clinit>(TgBox.java:60)
        ... 82 more
</pre>

I would it remove myself, but I looks like that Openllet does some more things with its logging, therefore I'm not sure about potential side effects...

**Comment by Galigator** [comment]
You should be able to remove the static bloc in shared/logging.java without side effect.

**Comment by Galigator** [comment]
[Link to @jpdigital patch with removal of limitation for Java EE](https://github.com/jpdigital/openllet/commit/f7ce306d94f721794ad44ba787f4440a0d2a0e51).
