### ISSUE TITLE
Deploying the project to the Maven's repository

### ISSUE THREAD

**Issue by trojczak** [Galigator/openllet#5]
Could you please deploy this project to the central Maven's repository? I would be easier to retrieve it from the repository than installing it manually on machines.

**Comment by Galigator** [comment]
The version 2.5.1 will be put into a public repository.
previous version doesn't match the requirements : http://central.sonatype.org/pages/requirements.html

Maybe there is other way, but I don't know it.

**Comment by trojczak** [comment]
Ok, thank you for your answer. Do you know when you will release the version 2.5.1?

**Comment by Galigator** [comment]
I am working on it. The goal of the 2.5.1 is to resolve every warnings and regression introduced in the 2.5.0 

Maybe one month ?

**Comment by trojczak** [comment]
Ok, so I keep my finger crossed then.

**Comment by Galigator** [comment]
I have start the process of publishing into central repository.
My account is under validation by the sonatype team.
When accepted, I will close the 2.5.1

**Comment by Galigator** [comment]
# Done.

```
		<dependency>
			<groupId>com.github.galigator.openllet</groupId>
			<artifactId>openllet-owlapi</artifactId>
			<version>2.5.1</version>
		</dependency>
```

**Comment by trojczak** [comment]
Ok, great! Thanks!
