### ISSUE TITLE
class file has wrong version 54.0, should be 52.0

### ISSUE THREAD

**Issue by marcelomachado** [Galigator/openllet#58]
I am trying to use the `OpenlletReasonerFactory` from version 2.6.5 as you can see in maven dependency below:

```
<dependency>
            <groupId>com.github.galigator.openllet</groupId>
            <artifactId>openllet-owlapi</artifactId>
            <version>2.6.5</version>
 </dependency>
```

However, when I try to build my project with IntelliJ the error `class file has wrong version 54.0, should be 52.0` appears. I am using Java 8:

<img width="670" alt="Screen Shot 2021-04-27 at 13 34 56" src="https://user-images.githubusercontent.com/5925863/116278997-66988200-a75d-11eb-8f31-9f5b090dc9dc.png">

<img width="446" alt="Screen Shot 2021-04-27 at 13 35 55" src="https://user-images.githubusercontent.com/5925863/116279131-8fb91280-a75d-11eb-81ec-ff84255a90cd.png">

<img width="667" alt="Screen Shot 2021-04-27 at 13 40 50" src="https://user-images.githubusercontent.com/5925863/116279701-3bfaf900-a75e-11eb-9d55-43f02ae51d7f.png">

Do I really need to update my Java version? What version of Openllet works with Java 8?

**Comment by Galigator** [comment]
The version 2.6.5 is build for java 11. If you require the deprecated version java 8 you should use the 2.6.4
Upgrade from java 8 to java 11 is the main change between 2.6.4 and 2.6.5

**Comment by marcelomachado** [comment]
@Galigator Thank you. 

Perhaps it would be interesting to have a note about this in README because it indicates java 8 as a requirement.
