### ISSUE TITLE
replace travis-ci.org with different ci service

### ISSUE THREAD

**Issue by cknoll** [Galigator/openllet#68]
Currently there is this badge inclueded in the README.md: 
[![Build Status](https://api.travis-ci.org/Galigator/openllet.svg?branch=integration)](https://travis-ci.org/Galigator/openllet) 

However at the linked website one reads: 

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on. 

This means a different ci service has to be choosen. (I made some positive experiences with [circleci](https://circleci.com/signup/?source-button=free)).

**Comment by cknoll** [comment]
To make use of circleci for this repo, the repo admin @Galigator has to create the according project (and thus have an account at circleci). I – although repo member – can only copy the [invite link](https://app.circleci.com/settings/project/github/Galigator/openllet?utm_campaign=locked_project&utm_content=project_dashboard_tooltip&utm_medium=copy_admin_project_set_up_link&utm_source=circleci_onboarding).

**Comment by berezovskyi** [comment]
Maybe it's easier to just use Github Actions?
