### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:4.1.0:bundle 

### ISSUE THREAD

**Issue by lucaturchet** [Galigator/openllet#71]
I get this error when launching the openllet.sh (I am on a mac, with JDK 17.02, I tried with JDK 16.02, but the issue persists)

[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:4.1.0:bundle (default-bundle) on project openllet-protege: Execution default-bundle of goal org.apache.felix:maven-bundle-plugin:4.1.0:bundle failed.: ConcurrentModificationException -> [Help 1]

There should be an issue in the POM.xml, but I can't figure out what is

**Comment by Galigator** [comment]
This is a know issue of apache.felix on jdk 15+ . I have fixed that yesterday with appropriate version changes.
